# Generated by Django 5.1.3 on 2024-11-25 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='places/photos/')),
                ('opening_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('is_open', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='place',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rating',
            name='cafe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='main.cafe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='cafe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.cafe'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'cafe')},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='place',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
