# Generated by Django 5.1.3 on 2024-11-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cafe_remove_review_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='is_open',
        ),
    ]
